Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.define "web01" do |web01|
    web01.vm.box = "bento/ubuntu-22.04"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.12"
    web01.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "1024"
      vb.cpus = "2"
    end
    web01.vm.provision "shell", inline: <<-SHELL
      sudo apt-get install -y ssh wget unzip curl
      sudo useradd -m -s /bin/bash -p "$(openssl passwd -1 MyPassword)" uadmin
      sudo usermod -aG sudo uadmin
    SHELL
  end

  config.vm.define "web02" do |web02|
    web02.vm.box = "bento/ubuntu-22.04"
    web02.vm.hostname = "web02"
    web02.vm.network "private_network", ip: "192.168.56.122"
    web02.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "1024"
      vb.cpus = "2"
    end
    web02.vm.provision "shell", inline: <<-SHELL
      sudo apt-get install -y ssh wget unzip curl
      sudo useradd -m -s /bin/bash -p "$(openssl passwd -1 MyPassword)" uadmin
      sudo usermod -aG sudo uadmin
    SHELL
  end
end
