Vagrant.configure("2") do |config|
    config.vm.define "microserv" do |microserv|    
        microserv.vm.box = "bento/ubuntu-22.04"
        microserv.vm.network "private_network", ip: "192.168.56.12"
        microserv.vm.provider "vmware_desktop" do |vmware|
            vmware.gui = true
            vmware.memory = "2048"
            vmware.cpus = "2"
        end
        microserv.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update && sudo apt-get upgrade
            sudo apt-get install -y ssh wget net-tools curl unzip nmap
			sudo useradd -m -s /bin/bash -p "$(openssl passwd -1 adminpasswd)" adminuser
			sudo usermod -aG sudo adminuser
        SHELL
    end
end
